//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto_SendLog
    {
        public int LogId { get; set; }
        public string LogName { get; set; }
        public string LogType { get; set; }
        public Nullable<int> LogStatus { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
    }
}
