//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC_SHORTURL
    {
        public int URL_ID { get; set; }
        public string URL_SHORT { get; set; }
        public string URL_LONG { get; set; }
        public string URL_MOBILE { get; set; }
        public string URL_VIPNO { get; set; }
        public string URL_PRINTNAME { get; set; }
        public string URL_DATE { get; set; }
        public string URL_COPY { get; set; }
        public Nullable<System.DateTime> URL_SENDTIME { get; set; }
        public Nullable<System.DateTime> URL_CREATETIME { get; set; }
        public string URL_FILENAME { get; set; }
    }
}
