//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSMS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC_Notice
    {
        public int Notice_Id { get; set; }
        public string Notice_Title { get; set; }
        public string Notice_Email { get; set; }
        public int Notice_Status { get; set; }
        public System.DateTime Notice_Date { get; set; }
    }
}
