//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShortUrl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC_Members
    {
        public int Mem_Id { get; set; }
        public string Mem_VipNo { get; set; }
        public string Mem_Mobile { get; set; }
        public string Mem_PrintName { get; set; }
        public string Mem_FirstName { get; set; }
        public string Mem_LastName { get; set; }
        public string Mem_CommId { get; set; }
        public string Mem_LongUrl { get; set; }
        public string Mem_Flag { get; set; }
        public bool Mem_IsDeal { get; set; }
        public Nullable<System.DateTime> Mem_CreateDate { get; set; }
    }
}
