//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShortUrl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC_ShortUrlList
    {
        public int Short_Id { get; set; }
        public string Short_Mobile { get; set; }
        public string Short_VipNo { get; set; }
        public string Short_LongUrl { get; set; }
        public string Short_ShortUrl { get; set; }
        public string Short_Flag { get; set; }
        public string Short_CommId { get; set; }
        public Nullable<System.DateTime> Short_CreateDate { get; set; }
    }
}
