//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSMS.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LC_AUTOFILE> LC_AUTOFILE { get; set; }
        public virtual DbSet<LC_ExceptionLog> LC_ExceptionLog { get; set; }
        public virtual DbSet<LC_Notice> LC_Notice { get; set; }
        public virtual DbSet<TD_List> TD_List { get; set; }
        public virtual DbSet<YM_SendList> YM_SendList { get; set; }
        public virtual DbSet<LC_SHORTURL> LC_SHORTURL { get; set; }
    }
}
