//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_BL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTP_FILE
    {
        public int FILEID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> DATES { get; set; }
        public string TIER { get; set; }
        public string LASTNAME { get; set; }
        public string TITLE { get; set; }
        public string CUTOFFDATE { get; set; }
        public string COSSPEND { get; set; }
        public string SPENDTONEXTTIER { get; set; }
        public string COPY { get; set; }
        public string MOBILE { get; set; }
    }
}
