//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_BL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC_ExceptionLog
    {
        public int Log_Id { get; set; }
        public string Log_Name { get; set; }
        public string Log_Url { get; set; }
        public string Log_Descr { get; set; }
        public string Log_Type { get; set; }
        public System.DateTime Log_Time { get; set; }
    }
}
