//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_BL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Auto_Bl_Entities : DbContext
    {
        public Auto_Bl_Entities()
            : base("name=Auto_Bl_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FTP_FILE> FTP_FILE { get; set; }
        public virtual DbSet<LC_ExceptionLog> LC_ExceptionLog { get; set; }
        public virtual DbSet<TD_List> TD_List { get; set; }
        public virtual DbSet<YM_SendList> YM_SendList { get; set; }
    }
}
