//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC.Survey.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BFSMSDBEntities : DbContext
    {
        public BFSMSDBEntities()
            : base("name=BFSMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<POSTSURVEY_FILES> POSTSURVEY_FILES { get; set; }
        public virtual DbSet<POSTSURVEY_LOG> POSTSURVEY_LOG { get; set; }
        public virtual DbSet<POSTSURVEY_SHORTURL> POSTSURVEY_SHORTURL { get; set; }
        public virtual DbSet<YM_SendList> YM_SendList { get; set; }
        public virtual DbSet<TD_List> TD_List { get; set; }
    }
}
