//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC.Survey.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTSURVEY_SHORTURL
    {
        public int ID { get; set; }
        public Nullable<int> FILE_ID { get; set; }
        public string COPY { get; set; }
        public string LONG_URL { get; set; }
        public string SHORT_URL { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
    }
}
