//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC.Survey.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTSURVEY_FILES
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string user_id { get; set; }
        public string card_type_datamart { get; set; }
        public string Title { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string customer_name_shortened_chi { get; set; }
        public string phone_country_code { get; set; }
        public string phone_area_code { get; set; }
        public string phone_no { get; set; }
        public string cust_type { get; set; }
        public string recent_store { get; set; }
        public string COMM_ID { get; set; }
        public string URL { get; set; }
        public string Seeding { get; set; }
        public string Expired_date { get; set; }
        public Nullable<System.DateTime> DownLoadTime { get; set; }
        public string Short_Url { get; set; }
        public string Copy { get; set; }
    }
}
