//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC.Survey.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_List
    {
        public int Id { get; set; }
        public string Mobile { get; set; }
        public string Conetents { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public string Types { get; set; }
    }
}
