//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC_OperateLog
    {
        public int Operate_Id { get; set; }
        public string Operate_Name { get; set; }
        public string Operate_FileName { get; set; }
        public System.DateTime Operate_Time { get; set; }
        public string Operate_Type { get; set; }
        public Nullable<int> Operate_Status { get; set; }
        public string Operate_Remark { get; set; }
    }
}
