//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LC_AUTOFILE
    {
        public int ID { get; set; }
        public string vip_no { get; set; }
        public string card_type { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string print_name { get; set; }
        public string phone_country_code { get; set; }
        public string phone_area_code { get; set; }
        public string phone_no { get; set; }
        public string cust_type { get; set; }
        public string recent_store { get; set; }
        public string comm_ID { get; set; }
        public string URL { get; set; }
        public string SEEDING { get; set; }
        public string Expired_date { get; set; }
        public string FILENAME { get; set; }
        public string Short_Url { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Copy { get; set; }
    }
}
