//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto_Offer
    {
        public int ID { get; set; }
        public string Vip_no { get; set; }
        public string Name { get; set; }
        public string phone_no { get; set; }
        public string Channel { get; set; }
        public string Language { get; set; }
        public string Offer { get; set; }
        public string Region { get; set; }
        public string CommID { get; set; }
        public string Date { get; set; }
        public string URL { get; set; }
        public string Flag { get; set; }
        public Nullable<int> OperateStatus { get; set; }
        public string ShortUrl { get; set; }
        public Nullable<bool> Td { get; set; }
        public string Copy { get; set; }
        public Nullable<int> AccountId { get; set; }
    }
}
